const PRODUCTS = {
  Chicken: ["Whole", "Cuts", "FPP", "Offals"],
  Beef: ["Vaccum", "Cubes and cuts", "FPP", "Bone in beef", "Offals"],
  Lamb: ["Cuts with bone", "Boneless cuts", "Offals"],
  Goat: ["Cuts with bone", "Boneless cuts", "Offals"]
};
const SUBPRODUCTS = {
  FPP: { Chicken: ["Franks", "Tender breast", "Hamburger", "Breaded products", "Minced chicken"], Beef: ["Skewers", "Minced beef", "Hamburgers", "Cubes", "Steaks", "Kebabs"], Lamb: ["Minced lamb", "Cubes with bone", "Boneless cubes", "Kebabs"], Goat: ["Minced lamb", "Cubes with bone", "Boneless cubes", "Kebabs"] },
  Cuts: { Chicken: ["Boneless breast", "Breast with bones", "Whole leg", "Drumsticks", "Thighs", "Whole wings"] }
};
const COUNTRIES = ["UAE", "Oman", "KSA", "Qatar", "Bahrain", "Kuwait", "Iraq", "Yemen"];
const CITIES = { Oman: ["Muscat", "Salalah", "Sohar", "Ibri", "Nizwa", "Dhank"], UAE: ["Dubai", "Sharjah", "Abu Dhabi", "Al Ain", "Fujairah"], Qatar: ["Doha"] };
const CURRENCIES = { UAE: "AED", Oman: "OMR", KSA: "SAR", Qatar: "QAR", Bahrain: "BHD", Kuwait: "KWD", Iraq: "IQD", Yemen: "YER" };
const FX_TO_USD = { USD: 1, AED: 3.6725, OMR: 0.3845, SAR: 3.75, QAR: 3.64, BHD: 0.376, KWD: 0.306, IQD: 1310, YER: 250 };
const STORAGE_KEY = "pricescope-records";
const LEGACY = { Frango: "Chicken", Bovino: "Beef", Carneiro: "Lamb", Congelado: "Frozen", Resfriado: "Chilled", "Bahrein": "Bahrain", Kwait: "Kuwait", Iemen: "Yemen", "Inteiro": "Whole", "Cortes": "Cuts", "Cortes com osso": "Cuts with bone", Desossado: "Boneless cuts", "Vácuo": "Vaccum", "Cubos e cortes": "Cubes and cuts", "Hambúrguer": "Hamburger", Moída: "Minced beef", "Carne com osso": "Bone in beef" };
let records = JSON.parse(localStorage.getItem(STORAGE_KEY) || "[]").map(record => Object.fromEntries(Object.entries(record).map(([key, value]) => [key, typeof value === "string" && LEGACY[value] ? LEGACY[value] : value])));
let editingId = null, recognition = null;
const $ = id => document.getElementById(id);
const number = value => Number(value) || 0;
const today = () => new Date().toISOString().slice(0, 10);
const money = (value, currency = "USD") => value === "" || value == null || Number.isNaN(Number(value)) ? "—" : new Intl.NumberFormat("en-US", { style: "currency", currency }).format(Number(value));
const escapeHtml = value => String(value ?? "").replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" }[c]));
function save() { localStorage.setItem(STORAGE_KEY, JSON.stringify(records)); render(); }
function showToast(text) { const toast = $("toast"); toast.textContent = text; toast.classList.add("show"); setTimeout(() => toast.classList.remove("show"), 2800); }
function populateRetailerSuggestions() { const names = [...new Set(records.map(record => record.store).filter(Boolean))].sort(); $("retailerSuggestions").innerHTML = names.map(name => `<option value="${escapeHtml(name)}"></option>`).join(""); }
function populateProducts(selected = "") { const options = PRODUCTS[$("protein").value] || []; $("product").innerHTML = `<option value="">Select</option>${options.map(item => `<option ${item === selected ? "selected" : ""}>${item}</option>`).join("")}`; populateSubProducts(); }
function populateSubProducts(selected = "") { const protein = $("protein").value, product = $("product").value, options = SUBPRODUCTS[product]?.[protein] || []; $("subProduct").innerHTML = `<option value="">Not applicable</option>${options.map(item => `<option ${item === selected ? "selected" : ""}>${item}</option>`).join("")}`; }
function populateCountryFields(country = $("country").value, city = "") {
  $("countryCustom").hidden = country !== "__custom"; $("countryCustom").required = country === "__custom";
  const cities = CITIES[country] || []; $("city").innerHTML = `<option value="">${cities.length ? "Select" : "Enter if needed"}</option>${cities.map(item => `<option ${item === city ? "selected" : ""}>${item}</option>`).join("")}<option value="__custom">Other city...</option>`;
  const custom = Boolean(city && !cities.includes(city)); $("city").value = custom ? "__custom" : $("city").value; $("cityCustom").hidden = !custom && $("city").value !== "__custom"; $("cityCustom").required = custom || $("city").value === "__custom"; if (custom) $("cityCustom").value = city;
  if (CURRENCIES[country]) $("currency").value = CURRENCIES[country];
}
function toggleConditionalFields() { $("fullPriceField").hidden = !$("promotion").checked; const hidden = !$("promoPack").checked; ["comboQtyField", "comboWeightField", "comboPriceField"].forEach(id => $(id).hidden = hidden); updateCalculation(); }
function openDialog(record = null, photo = null, transcript = "") {
  editingId = record?.id || null; $("entryForm").reset(); $("date").value = record?.date || today(); $("dialogEyebrow").textContent = editingId ? "EDIT COLLECTION" : "NEW COLLECTION"; $("dialogTitle").textContent = editingId ? "Edit price" : "Add price";
  if (record) {
    $("country").value = COUNTRIES.includes(record.country) ? record.country : "__custom"; $("countryCustom").value = COUNTRIES.includes(record.country) ? "" : record.country; populateCountryFields($("country").value, record.city);
    for (const key of ["collector", "channel", "store", "protein", "temperature", "weight", "packPrice", "priceKg", "priceUsdKg", "margin", "industryPrice", "currency", "fullPrice", "subProduct", "comboQty", "comboUnitWeight", "comboTotalPrice"]) if ($(key)) $(key).value = record[key] ?? "";
    if (record.city && !CITIES[record.country]?.includes(record.city)) { $("city").value = "__custom"; $("cityCustom").value = record.city; $("cityCustom").hidden = false; }
    $("promotion").checked = Boolean(record.promotion); $("promoPack").checked = Boolean(record.promoPack); $("protein").value = record.protein; populateProducts(record.product); populateSubProducts(record.subProduct);
  } else { $("margin").value = 20; populateProducts(); $("audioNotice").hidden = !transcript; $("transcriptText").textContent = transcript; }
  toggleConditionalFields(); $("photoNotice").hidden = !photo; if (photo) $("photoPreview").src = photo; $("entryDialog").showModal(); updateCalculation();
}
function closeDialog() { $("entryDialog").close(); editingId = null; }
function selectedCountry() { return $("country").value === "__custom" ? $("countryCustom").value.trim() : $("country").value; }
function selectedCity() { return $("city").value === "__custom" ? $("cityCustom").value.trim() : $("city").value; }
function calculatedWeight() { return $("promoPack").checked ? number($("comboQty").value) * number($("comboUnitWeight").value) : number($("weight").value); }
function calculatedPackPrice() { return $("promoPack").checked ? number($("comboTotalPrice").value) : number($("packPrice").value); }
function updateCalculation() {
  const weight = calculatedWeight(), packPrice = calculatedPackPrice(), marketPrice = number($("priceKg").value) || (weight ? packPrice / weight : 0), fx = FX_TO_USD[$("currency").value] || 1, manual = number($("industryPrice").value), margin = number($("margin").value), industry = manual || marketPrice * (1 - margin / 100);
  $("priceUsdKg").value = marketPrice ? (marketPrice / fx).toFixed(2) : ""; $("estimatedSale").textContent = industry ? money(industry, $("currency").value || "USD") : "—";
}
function recordFromForm() {
  const weight = calculatedWeight(), packPrice = calculatedPackPrice(), priceKg = number($("priceKg").value) || (weight ? packPrice / weight : 0), currency = $("currency").value, fx = FX_TO_USD[currency] || 1, manual = number($("industryPrice").value), margin = number($("margin").value);
  return { id: editingId || crypto.randomUUID(), date: $("date").value, collector: $("collector").value.trim(), channel: $("channel").value, city: selectedCity(), country: selectedCountry(), currency, store: $("store").value.trim(), protein: $("protein").value, temperature: $("temperature").value, product: $("product").value, subProduct: $("subProduct").value, weight, packPrice, priceKg, priceUsdKg: priceKg / fx, margin, industryPrice: manual || priceKg * (1 - margin / 100), manualIndustryPrice: Boolean(manual), promotion: $("promotion").checked, fullPrice: $("promotion").checked ? number($("fullPrice").value) : "", promoPack: $("promoPack").checked, comboQty: $("promoPack").checked ? number($("comboQty").value) : "", comboUnitWeight: $("promoPack").checked ? number($("comboUnitWeight").value) : "", comboTotalPrice: $("promoPack").checked ? number($("comboTotalPrice").value) : "" };
}
function filteredRecords() { const from = $("filterFrom").value, to = $("filterTo").value; return records.filter(r => (!from || r.date >= from) && (!to || r.date <= to) && (!$("filterCountry").value || r.country === $("filterCountry").value) && (!$("filterStore").value || r.store === $("filterStore").value) && (!$("filterProtein").value || r.protein === $("filterProtein").value) && (!$("filterTemp").value || r.temperature === $("filterTemp").value) && (!$("filterProduct").value || r.product === $("filterProduct").value)); }
function refreshFilterOptions() { const fill = (id, values, label) => { const current = $(id).value; $(id).innerHTML = `<option value="">${label}</option>${[...new Set(values.filter(Boolean))].sort().map(v => `<option ${v === current ? "selected" : ""}>${escapeHtml(v)}</option>`).join("")}`; }; fill("filterCountry", records.map(r => r.country), "All countries"); fill("filterStore", records.map(r => r.store), "All retailers"); fill("filterProduct", Object.values(PRODUCTS).flat(), "All"); }
function renderMetrics(data) { const prices = data.map(r => number(r.priceKg)).filter(Boolean), avg = prices.length ? prices.reduce((a, b) => a + b, 0) / prices.length : 0, max = prices.length ? Math.max(...prices) : 0; $("metrics").innerHTML = `<div class="metric"><small>Average price</small><strong>${money(avg, data[0]?.currency || "USD")}</strong><span>per filtered kg</span></div><div class="metric"><small>Maximum price</small><strong>${money(max, data[0]?.currency || "USD")}</strong><span>per filtered kg</span></div><div class="metric"><small>Temperature variation</small><strong>${money(temperatureVariation(data), data[0]?.currency || "USD")}</strong><span>lowest to highest per product</span></div><div class="metric"><small>Comparable groups</small><strong>${new Set(data.map(r => `${r.country}|${r.store}|${r.protein}|${r.product}`)).size}</strong><span>retailer, country and product</span></div>`; }
function temperatureVariation(data) { const groups = {}; data.forEach(r => { const key = `${r.country}|${r.protein}|${r.product}`; (groups[key] ||= {})[r.temperature] = number(r.priceKg); }); return Math.max(0, ...Object.values(groups).map(group => { const values = Object.values(group).filter(Boolean); return values.length > 1 ? Math.max(...values) - Math.min(...values) : 0; })); }
function render() { refreshFilterOptions(); populateRetailerSuggestions(); const data = filteredRecords(); $("recordCount").textContent = records.length; $("visibleCount").textContent = data.length; $("emptyState").style.display = data.length ? "none" : "block"; renderMetrics(data); $("priceTable").innerHTML = data.map(r => `<tr><td><input type="checkbox" class="row-check" data-id="${r.id}"></td><td>${r.date || "—"}</td><td><b>${escapeHtml(r.store)}</b><span class="subtle">${escapeHtml(r.collector || "")} · ${escapeHtml(r.channel || "")}</span></td><td><span class="product-name">${escapeHtml(r.protein)}</span><span class="subtle">${escapeHtml(r.product)}${r.subProduct ? ` · ${escapeHtml(r.subProduct)}` : ""}${r.promotion ? " · Promotion" : ""}</span></td><td><span class="tag ${r.temperature === "Frozen" ? "cold" : ""}">${r.temperature}</span></td><td class="price">${money(r.priceKg, r.currency || "USD")}</td><td class="price teal-price">${money(r.priceUsdKg)}</td><td class="price teal-price">${money(r.industryPrice, r.currency || "USD")}</td><td><button class="row-action edit-row" data-id="${r.id}" title="Edit">✎</button></td></tr>`).join(""); renderInsights(data); $("deleteSelected").style.display = data.length ? "block" : "none"; }
function renderInsights(data) { const avg = data.length ? data.reduce((sum, r) => sum + number(r.priceKg), 0) / data.length : 0, below = data.filter(r => number(r.priceKg) < avg).slice(0, 5); $("insights").innerHTML = below.length ? below.map(r => `<div class="insight"><div><b>${escapeHtml(r.product)}</b><small>${escapeHtml(r.store)} · ${escapeHtml(r.country)}</small></div><strong>${money(r.priceKg, r.currency || "USD")}</strong></div>`).join("") : `<div class="empty-state"><span>Below-average prices will appear here.</span></div>`; }
function csvCell(value) { return `"${String(value ?? "").replace(/"/g, '""')}"`; }
function exportCsv() { const headers = ["id", "date", "collector", "channel", "city", "country", "currency", "retailer", "protein", "temperature", "product", "sub_product", "package_weight_kg", "package_price", "price_kg_rsp_label", "price_usd_kg", "retailer_margin_pct", "industry_price", "manual_industry_price", "promotion", "full_price", "promo_pack", "combo_quantity", "combo_unit_weight_kg", "combo_total_price"]; const rows = records.map(r => [r.id, r.date, r.collector, r.channel, r.city, r.country, r.currency, r.store, r.protein, r.temperature, r.product, r.subProduct, r.weight, r.packPrice, r.priceKg, r.priceUsdKg, r.margin, r.industryPrice, r.manualIndustryPrice, r.promotion, r.fullPrice, r.promoPack, r.comboQty, r.comboUnitWeight, r.comboTotalPrice]); const blob = new Blob(["\ufeff" + [headers, ...rows].map(row => row.map(csvCell).join(";")).join("\r\n")], { type: "text/csv;charset=utf-8" }), a = document.createElement("a"); a.href = URL.createObjectURL(blob); a.download = `pricescope-${today()}.csv`; a.click(); URL.revokeObjectURL(a.href); showToast("File exported for Excel."); }
function parseCsv(text) { const lines = text.replace(/^\ufeff/, "").split(/\r?\n/).filter(Boolean), split = line => line.match(/(?:^|;)("(?:[^"]|"")*"|[^;]*)/g)?.map(v => v.replace(/^;/, "").replace(/^"|"$/g, "").replace(/""/g, '"')) || [], headers = split(lines.shift()).map(h => h.toLowerCase()); return lines.map(line => { const values = split(line), get = key => values[headers.indexOf(key)] || "", currency = get("currency") || CURRENCIES[get("country")] || "USD", priceKg = number(get("price_kg_rsp_label")); return { id: get("id") || crypto.randomUUID(), date: get("date"), collector: get("collector"), channel: get("channel"), city: get("city"), country: get("country"), currency, store: get("retailer"), protein: get("protein"), temperature: get("temperature"), product: get("product"), subProduct: get("sub_product"), weight: number(get("package_weight_kg")), packPrice: number(get("package_price")), priceKg, priceUsdKg: number(get("price_usd_kg")) || priceKg / (FX_TO_USD[currency] || 1), margin: number(get("retailer_margin_pct")), industryPrice: number(get("industry_price")), manualIndustryPrice: get("manual_industry_price") === "true", promotion: get("promotion") === "true", fullPrice: number(get("full_price")), promoPack: get("promo_pack") === "true", comboQty: number(get("combo_quantity")), comboUnitWeight: number(get("combo_unit_weight_kg")), comboTotalPrice: number(get("combo_total_price")) }; }); }
function startAudio() { const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition; if (!SpeechRecognition) { showToast("Your browser does not support transcription."); openDialog(); return; } recognition = new SpeechRecognition(); recognition.lang = "en-US"; recognition.interimResults = false; showToast("Recording: speak retailer, country, product, temperature and price."); recognition.onresult = event => { const text = event.results[0][0].transcript; openDialog(null, null, text); $("city").focus(); showToast("Transcript received. Complete the fields and save."); }; recognition.onerror = () => showToast("Transcription failed. Please try again."); recognition.start(); }
$("manualBtn").onclick = () => openDialog(); $("closeDialog").onclick = closeDialog; $("cancelDialog").onclick = closeDialog; $("country").onchange = () => populateCountryFields(); $("city").onchange = () => { $("cityCustom").hidden = $("city").value !== "__custom"; $("cityCustom").required = $("city").value === "__custom"; }; $("protein").onchange = () => populateProducts(); $("product").onchange = () => populateSubProducts(); ["weight", "packPrice", "priceKg", "industryPrice", "margin", "currency", "comboQty", "comboUnitWeight", "comboTotalPrice"].forEach(id => $(id).oninput = updateCalculation); $("promotion").onchange = toggleConditionalFields; $("promoPack").onchange = toggleConditionalFields;
$("entryForm").onsubmit = event => { event.preventDefault(); const item = recordFromForm(), index = records.findIndex(r => r.id === item.id); if (index >= 0) records[index] = item; else records.unshift(item); save(); closeDialog(); showToast(index >= 0 ? "Collection updated." : "Collection saved."); };
document.querySelectorAll(".filters input,.filters select").forEach(el => el.addEventListener("change", render)); $("clearFilters").onclick = () => { document.querySelectorAll(".filters input,.filters select").forEach(el => el.value = ""); render(); }; $("priceTable").onclick = event => { const button = event.target.closest(".edit-row"); if (button) openDialog(records.find(r => r.id === button.dataset.id)); }; $("selectAll").onchange = event => document.querySelectorAll(".row-check").forEach(c => c.checked = event.target.checked); $("deleteSelected").onclick = () => { const ids = [...document.querySelectorAll(".row-check:checked")].map(c => c.dataset.id); if (ids.length && confirm(`Delete ${ids.length} collection(s)?`)) { records = records.filter(r => !ids.includes(r.id)); save(); showToast("Collections deleted."); } }; $("exportBtn").onclick = exportCsv; $("importInput").onchange = event => { const file = event.target.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { const imported = parseCsv(reader.result); records = [...imported, ...records.filter(old => !imported.some(item => item.id === old.id))]; save(); showToast(`${imported.length} record(s) imported.`); }; reader.readAsText(file, "UTF-8"); event.target.value = ""; }; $("photoBtn").onclick = () => $("photoInput").click(); $("photoInput").onchange = event => { const file = event.target.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => openDialog(null, reader.result); reader.readAsDataURL(file); event.target.value = ""; }; $("audioBtn").onclick = startAudio;
let deferredPrompt; window.addEventListener("beforeinstallprompt", event => { event.preventDefault(); deferredPrompt = event; $("installBtn").hidden = false; }); $("installBtn").onclick = async () => { if (deferredPrompt) { deferredPrompt.prompt(); deferredPrompt = null; $("installBtn").hidden = true; } }; if ("serviceWorker" in navigator) window.addEventListener("load", () => navigator.serviceWorker.register("sw.js")); render();
