const PRODUCTS = {
  Frango: ["Inteiro", "Cortes", "FPP"],
  Bovino: ["Vácuo", "Cubos e cortes", "Hambúrguer", "Moída", "Carne com osso"],
  Carneiro: ["Cortes com osso", "Desossado"],
  Goat: ["Cortes com osso", "Desossado"]
};
const STORAGE_KEY = "pricescope-records";
let records = JSON.parse(localStorage.getItem(STORAGE_KEY) || "[]");
let editingId = null;
let recognition = null;
const $ = id => document.getElementById(id);
const money = value => value === "" || value == null || Number.isNaN(Number(value)) ? "—" : new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(Number(value));
const today = () => new Date().toISOString().slice(0, 10);
function save() { localStorage.setItem(STORAGE_KEY, JSON.stringify(records)); render(); }
function showToast(text) { const toast = $("toast"); toast.textContent = text; toast.classList.add("show"); setTimeout(() => toast.classList.remove("show"), 2800); }
function populateProducts(selected = "") { const protein = $("protein").value; $("product").innerHTML = `<option value="">Selecione</option>${(PRODUCTS[protein] || []).map(p => `<option ${p === selected ? "selected" : ""}>${p}</option>`).join("")}`; }
function openDialog(record = null, photo = null) {
  editingId = record?.id || null; $("entryForm").reset(); $("date").value = record?.date || today(); $("dialogEyebrow").textContent = editingId ? "EDITAR COLETA" : "NOVA COLETA"; $("dialogTitle").textContent = editingId ? "Editar preço" : "Adicionar preço";
  if (record) { for (const key of ["city", "country", "store", "protein", "temperature", "weight", "packPrice", "priceKg", "margin", "industryPrice", "rsp"]) if ($(key)) $(key).value = record[key] ?? ""; populateProducts(record.product); }
  else { $("margin").value = 20; populateProducts(); }
  if (photo) { $("photoNotice").hidden = false; $("photoPreview").src = photo; } else $("photoNotice").hidden = true;
  $("entryDialog").showModal(); updateCalculation();
}
function closeDialog() { $("entryDialog").close(); editingId = null; }
function updateCalculation() { const direct = Number($("industryPrice").value); const rsp = Number($("rsp").value); const margin = Number($("margin").value) || 0; const value = direct > 0 ? direct : rsp > 0 ? rsp * (1 - margin / 100) : 0; $("estimatedSale").textContent = value ? money(value) : "—"; }
function recordFromForm() { const weight = Number($("weight").value); const packPrice = Number($("packPrice").value); const priceKg = Number($("priceKg").value) || (weight ? packPrice / weight : 0); const direct = Number($("industryPrice").value); const rsp = Number($("rsp").value); const margin = Number($("margin").value) || 0; return { id: editingId || crypto.randomUUID(), date: $("date").value, city: $("city").value.trim(), country: $("country").value.trim(), store: $("store").value.trim(), protein: $("protein").value, temperature: $("temperature").value, product: $("product").value, weight, packPrice, priceKg, margin, industryPrice: direct || "", rsp: rsp || "", estimatedSale: direct || (rsp ? rsp * (1 - margin / 100) : "") }; }
function filteredRecords() { const from = $("filterFrom").value, to = $("filterTo").value; return records.filter(r => (!from || r.date >= from) && (!to || r.date <= to) && (!$("filterCountry").value || r.country === $("filterCountry").value) && (!$("filterStore").value || r.store === $("filterStore").value) && (!$("filterProtein").value || r.protein === $("filterProtein").value) && (!$("filterTemp").value || r.temperature === $("filterTemp").value) && (!$("filterProduct").value || r.product === $("filterProduct").value)); }
function refreshFilterOptions() { const fill = (id, values, label) => { const current = $(id).value; $(id).innerHTML = `<option value="">${label}</option>${[...new Set(values.filter(Boolean))].sort().map(v => `<option ${v === current ? "selected" : ""}>${v}</option>`).join("")}`; }; fill("filterCountry", records.map(r => r.country), "Todos os países"); fill("filterStore", records.map(r => r.store), "Todos os estabelecimentos"); const productValues = Object.values(PRODUCTS).flat(); fill("filterProduct", productValues, "Todos"); }
function render() { refreshFilterOptions(); const data = filteredRecords(); $("recordCount").textContent = records.length; $("visibleCount").textContent = data.length; $("emptyState").style.display = data.length ? "none" : "block"; $("priceTable").innerHTML = data.map(r => `<tr><td><input type="checkbox" class="row-check" data-id="${r.id}"></td><td>${r.date || "—"}</td><td><b>${escapeHtml(r.store)}</b><span class="subtle">${escapeHtml(r.city || r.country)}</span></td><td><span class="product-name">${escapeHtml(r.protein)}</span><span class="subtle">${escapeHtml(r.product)}</span></td><td><span class="tag ${r.temperature === "Congelado" ? "cold" : ""}">${r.temperature}</span></td><td>${Number(r.weight).toLocaleString("pt-BR")} kg<br><span class="subtle">${money(r.packPrice)}</span></td><td class="price">${money(r.priceKg)}</td><td>${money(r.rsp)}</td><td class="price teal-price">${money(r.estimatedSale)}</td><td><button class="row-action edit-row" data-id="${r.id}" title="Editar">✎</button></td></tr>`).join(""); renderInsights(data); $("deleteSelected").style.display = data.length ? "block" : "none"; }
function renderInsights(data) { const byProduct = {}; data.forEach(r => { (byProduct[r.product] ||= []).push(Number(r.priceKg)); }); const avg = data.length ? data.reduce((sum, r) => sum + Number(r.priceKg || 0), 0) / data.length : 0; const below = data.filter(r => Number(r.priceKg) < avg).sort((a, b) => a.priceKg - b.priceKg).slice(0, 5); $("insights").innerHTML = below.length ? below.map(r => `<div class="insight"><div><b>${escapeHtml(r.product)}</b><small>${escapeHtml(r.store)} · ${escapeHtml(r.protein)}</small></div><strong>${money(r.priceKg)}</strong></div>`).join("") : `<div class="empty-state"><span>Os preços abaixo da média aparecerão aqui.</span></div>`; }
function escapeHtml(value) { return String(value ?? "").replace(/[&<>"']/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" }[char])); }
function csvCell(value) { return `"${String(value ?? "").replace(/"/g, '""')}"`; }
function exportCsv() { const headers = ["id", "data", "cidade", "pais", "estabelecimento", "proteina", "temperatura", "produto", "peso_embalagem_kg", "preco_embalagem", "preco_kg", "margem_revendedor_pct", "preco_industria_retailer", "rsp_consumidor_kg", "venda_estimada"]; const rows = records.map(r => [r.id, r.date, r.city, r.country, r.store, r.protein, r.temperature, r.product, r.weight, r.packPrice, r.priceKg, r.margin, r.industryPrice, r.rsp, r.estimatedSale]); const blob = new Blob(["\ufeff" + [headers, ...rows].map(row => row.map(csvCell).join(";")).join("\r\n")], { type: "text/csv;charset=utf-8" }); const a = document.createElement("a"); a.href = URL.createObjectURL(blob); a.download = `pricescope-${today()}.csv`; a.click(); URL.revokeObjectURL(a.href); showToast("Arquivo exportado para o Excel."); }
function parseCsv(text) { const lines = text.replace(/^\ufeff/, "").split(/\r?\n/).filter(Boolean); const split = line => line.match(/(?:^|;)("(?:[^"]|"")*"|[^;]*)/g)?.map(v => v.replace(/^;/, "").replace(/^"|"$/g, "").replace(/""/g, '"')) || []; const headers = split(lines.shift()).map(h => h.toLowerCase()); return lines.map(line => { const values = split(line); const get = key => values[headers.indexOf(key)] || ""; return { id: get("id") || crypto.randomUUID(), date: get("data"), city: get("cidade"), country: get("pais"), store: get("estabelecimento"), protein: get("proteina"), temperature: get("temperatura"), product: get("produto"), weight: Number(get("peso_embalagem_kg")) || 0, packPrice: Number(get("preco_embalagem")) || 0, priceKg: Number(get("preco_kg")) || 0, margin: Number(get("margem_revendedor_pct")) || 0, industryPrice: Number(get("preco_industria_retailer")) || "", rsp: Number(get("rsp_consumidor_kg")) || "", estimatedSale: Number(get("venda_estimada")) || "" }; }); }
function applyTranscript(text) { const lower = text.toLowerCase(); const protein = lower.includes("frango") ? "Frango" : lower.includes("bovino") || lower.includes("boi") || lower.includes("carne") ? "Bovino" : lower.includes("carneiro") || lower.includes("lamb") ? "Carneiro" : lower.includes("goat") || lower.includes("cabra") ? "Goat" : ""; if (protein) { $("protein").value = protein; populateProducts(); const product = Object.values(PRODUCTS[protein]).find(item => lower.includes(item.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, ""))); if (product) $("product").value = product; } if (lower.includes("congel")) $("temperature").value = "Congelado"; else if (lower.includes("resfri") || lower.includes("refrig")) $("temperature").value = "Resfriado"; const numbers = [...text.matchAll(/(\d+(?:[,.]\d+)?)/g)].map(match => Number(match[1].replace(",", "."))); if (numbers.length >= 2) { $("weight").value = numbers[0]; $("packPrice").value = numbers[1]; } else if (numbers.length === 1) $("packPrice").value = numbers[0]; updateCalculation(); }
function startAudio() { const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition; if (!SpeechRecognition) { showToast("Seu navegador não oferece transcrição de áudio."); openDialog(); return; } recognition = new SpeechRecognition(); recognition.lang = "pt-BR"; recognition.interimResults = false; $("audioBtn").classList.add("recording"); showToast("Gravando: fale estabelecimento, país, produto, temperatura e preço."); recognition.onresult = event => { const text = event.results[0][0].transcript; openDialog(); $("audioNotice").hidden = false; $("transcriptText").textContent = text; applyTranscript(text); $("city").focus(); showToast("Campos reconhecidos. Complete os dados que faltarem e salve."); }; recognition.onerror = () => { $("audioBtn").classList.remove("recording"); showToast("Não foi possível transcrever. Tente novamente."); }; recognition.onend = () => $("audioBtn").classList.remove("recording"); recognition.start(); }
$("manualBtn").onclick = () => openDialog(); $("closeDialog").onclick = closeDialog; $("cancelDialog").onclick = closeDialog; $("protein").onchange = () => populateProducts(); ["weight", "packPrice", "industryPrice", "rsp", "margin"].forEach(id => $(id).oninput = updateCalculation); $("entryForm").onsubmit = event => { event.preventDefault(); const item = recordFromForm(); const index = records.findIndex(r => r.id === item.id); if (index >= 0) records[index] = item; else records.unshift(item); save(); closeDialog(); showToast(index >= 0 ? "Coleta atualizada." : "Coleta salva."); };
document.querySelectorAll(".filters input,.filters select").forEach(el => el.addEventListener("change", render)); $("clearFilters").onclick = () => { document.querySelectorAll(".filters input,.filters select").forEach(el => el.value = ""); render(); }; $("priceTable").onclick = event => { const button = event.target.closest(".edit-row"); if (button) openDialog(records.find(r => r.id === button.dataset.id)); }; $("selectAll").onchange = event => document.querySelectorAll(".row-check").forEach(c => c.checked = event.target.checked); $("deleteSelected").onclick = () => { const ids = [...document.querySelectorAll(".row-check:checked")].map(c => c.dataset.id); if (ids.length && confirm(`Excluir ${ids.length} coleta(s)?`)) { records = records.filter(r => !ids.includes(r.id)); save(); showToast("Coletas excluídas."); } }; $("exportBtn").onclick = exportCsv; $("importInput").onchange = event => { const file = event.target.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { const imported = parseCsv(reader.result); records = [...imported, ...records.filter(old => !imported.some(item => item.id === old.id))]; save(); showToast(`${imported.length} registro(s) importado(s).`); }; reader.readAsText(file, "UTF-8"); event.target.value = ""; }; $("photoBtn").onclick = () => $("photoInput").click(); $("photoInput").onchange = event => { const file = event.target.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => openDialog(null, reader.result); reader.readAsDataURL(file); event.target.value = ""; }; $("audioBtn").onclick = startAudio;
let deferredPrompt; window.addEventListener("beforeinstallprompt", event => { event.preventDefault(); deferredPrompt = event; $("installBtn").hidden = false; }); $("installBtn").onclick = async () => { if (deferredPrompt) { deferredPrompt.prompt(); deferredPrompt = null; $("installBtn").hidden = true; } }; if ("serviceWorker" in navigator) window.addEventListener("load", () => navigator.serviceWorker.register("sw.js")); render();
